# Assignment 1 IRS

Information retrieval is the process of obtaining information system resources that are relevant to an information need from a collection of those resources. The core purpose of this assignment is to give you the flavor of IRS. You need to follow some steps listed below and in the end, you'll be able to build your own small IRS. So, let's start.

In [66]:
# required imports
import numpy as np
import fnmatch
import os



Suppose we have 3 files containing data :

### File Contents

<img src="1.png"/>
<img src="2.png"/>
<img src="3.png"/>

# Step 1 Create Files with Dummy data

You have to create few files with dummy data of your own choice as shown above.

# Step 2 Traverse Directories

 Now, You have to traverse the directories and store all the files into a dict type variable(files_dict). 

In [67]:
# Here we have intialized some variables, you can add more if required.

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set
unique_word_dict = {}      # dictionary of unique words


In [68]:
#Your code starts here   
FOLDER = os.getcwd()
s = os.listdir(FOLDER)

for file in s:
    if file not in files_dict:
        if file != 'IRS.ipynb':
            files_dict[file] = file_count
            file_count+=1

#Your code ends here       

Displaying the count of files.

In [69]:
print("\nTotal Number  of files\n", file_count)


Total Number  of files
 4


Displaying Dictionary containing all files.

In [70]:
print("\nDictionary containing  files\n", files_dict)


Dictionary containing  files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2, 'test.txt': 3}


# Step 3 Extract Unique Vocabulary

In [71]:
# write code to print all the unique words in every file and store them in a set

In [72]:
#Your code starts here  
lst = []  
count = 0
for key in files_dict:
    fhand = open(key)
    for line in fhand:
        line = line.split()
        for word in line:
            if word[0].isupper():
                new_word = word.lower()
                index = line.index(word)
                line[index] = new_word
            if word[-1] == '.':
                index = line.index(word)
                new_word = word[:-1]
                line[index] = new_word   
        lst = lst+ line
    fhand.close()
unique_word_set = set(lst)

print("\nUnique words in files\n", unique_word_set)
#Your code ends here


Unique words in files
 {'pen', 'book', 'my', 'is', 'this', 'interesting'}


### Expected Output

<img src="4.png"/>

# Step 4 Create Term Document Matrix

Create Term-Doc-matrix using Bag of word approach.and display its contents initially and finally.

In [73]:
# Create Term doc matrix such that colmns will be unique words and all the files will be rows
# Write code to count all the unique words appearances in all the files and store it in a dictionary for words 

In [74]:
#Your code starts here    
count = 0
unique_word_dict = {}
for word in unique_word_set:
    unique_word_dict[word] = count
    count+=1



col = len(unique_word_dict)
print("TERM DOC MATRIX Initially")
termMatrix =  np.zeros((file_count, col))
print (termMatrix)

print ("\ndictionary of unique words\n",unique_word_dict)
print("\ndictionary of files\n", files_dict)

#Your code ends here

TERM DOC MATRIX Initially
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

dictionary of unique words
 {'pen': 0, 'book': 1, 'my': 2, 'is': 3, 'this': 4, 'interesting': 5}

dictionary of files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2, 'test.txt': 3}


### Expected Output

<img src="5.png"/>

# Step 5 Fill Term Document Matrix

In [75]:
# Fill the term doc matrix by checking if the unique word exists in a file or not
# If it exists then substitute a 1 in term_doc_matrix (eg : TERM_DOC_MATRIX[file][word] = 1 ) 
# Do the same for all the files present in the directory

In [76]:
#Your code starts here

fileIndex = 0
for file in files_dict:
    fhand  = open(file, 'r')
    for line in fhand:
        line = line.split() 
        for i in line:
            word = i.lower()
            if i[-1] == '.':
                word = i[:-1]
                word = word.lower()   
            if word in unique_word_dict:    
                termMatrix[fileIndex][unique_word_dict[word]] = 1 
    fileIndex +=1
print('TERM DOC MATRIX after filling')
print(termMatrix)
    #Your code ends here


TERM DOC MATRIX after filling
[[0. 1. 1. 1. 1. 0.]
 [1. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]


### Expected Output

<img src="6.png"/>

# Step 6 Ask for a user Query

In [77]:
# For user query make a column vector of length of all the unique words present in a set

In [78]:
#Your code starts here    
Len_of_unique_word_set = len(unique_word_set)
col_vector = np.zeros((Len_of_unique_word_set,1))
print(col_vector)
#Your code ends here

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


### Expected Output

<img src="7.png"/>

In [79]:
query = input("\nWrite something for searching  ")
# Check every word of query if it exists in the set of unique words or not
# If exixts then increment the count of that word in word dictionary


In [80]:
#Your code starts here    

query= query.split()
for word in query:
    if word in unique_word_dict:
        col_vector [unique_word_dict[word]][0] +=1 
print(col_vector)
#Your code ends here

[[0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]]


### Expected Output

<img src="8.png"/>

# Step 7 Display Resultant Vector

Display 
1. Resultant vector.
2. Max value in resultant vector.
3. Index of max value in resultant vector.


In [114]:
#Your code starts here  
resultant_vector = np.dot(termMatrix,col_vector)
print(resultant_vector)
print("Maximum in resultant is   ", np.amax(resultant_vector) )
lst = list(resultant_vector)
max_index = lst.index(max(lst))
print( "    Index of maximum in resultant is  ",  max_index )
#Your code ends here

[[3.]
 [2.]
 [3.]
 [0.]]
Maximum in resultant is    3.0
    Index of maximum in resultant is   0


### Expected Output

<img src="9.png"/>

# Step 8 Display the contents of file


In [82]:
#Write the code to identify the file_name having maximum value in the resultant vector and display its contents.

In [135]:
#Your code starts here    
for file,index in files_dict.items():
    if index == max_index: 
        required_file = file

fhand = open(required_file,'r')
for line in fhand:
    print(line)


#print()
#Your code ends here

This is my book.


Congratulations Now you are able to build your own small IRS.